name: deploy
on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image to GHCR
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/dual-server:prod
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: SSH deploy (single container)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            IMAGE=ghcr.io/${{ github.repository_owner }}/dual-server:prod
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull "$IMAGE"
            docker stop dual-server || true
            docker rm dual-server || true
            docker run -d --name dual-server \
              --restart unless-stopped \
              -p 80:80 \
              "$IMAGE"
            docker image prune -f

